'use strict';
// Generated by sync-prayer-framework.cjs from prayer-framework.json.
window.PRAYER_GUIDE = [
  {
    "letter": "P",
    "word": "PULSE",
    "prompt": "How’s life?"
  },
  {
    "letter": "R",
    "word": "REFLECT",
    "prompt": "How has your time with God been?"
  },
  {
    "letter": "A",
    "word": "ATTUNE",
    "prompt": "What’s God teaching you?"
  },
  {
    "letter": "Y",
    "word": "YIELD",
    "prompt": "What are you struggling with?"
  },
  {
    "letter": "E",
    "word": "ENCOURAGE",
    "prompt": "Who can you encourage or draw closer to God?"
  },
  {
    "letter": "R",
    "word": "REQUEST",
    "prompt": "How can I pray for you?"
  }
];
